version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    restart: always
    ports:
      - "6000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/ecommerce"
      NEXT_PUBLIC_URL: "https://admin.shopdoan.shop"
      JWT_SECRET_KEY: "a-super-secret-key-for-admin-change-me"
      NODE_ENV: "development"
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ""
    depends_on:
      - db

  storefront:
    build:
      context: .
      dockerfile: apps/storefront/Dockerfile
    restart: always
    ports:
      - "6001:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/ecommerce"
      NEXT_PUBLIC_URL: "https://thanhlab.shopdoan.shop"
      NODE_ENV: "development"
    depends_on:
      - db

volumes:
  postgres_data:
